version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres  # Nazwa kontenera PostgreSQL
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "8080:5432"  # Mapowanie portu 5432 kontenera PostgreSQL na port 8080 hosta
    volumes:
      - pgdata:/var/lib/postgresql/data

  yourapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5157
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=postgres;Username=postgres;Password=admin;
    ports:
      - "5157:5157"
    depends_on:
      - postgres

volumes:
  pgdata:
